.travis.yml
  sudo: required

  language: generic

  services:
    - docker
  
  before_install:
    - echo "start create images"
    - docker build -t a2/react -f Dockerfile.dev .
  
  script:
    - docker run -e CI=true a2/react npm run test -- --coverage

  after_success:
    - echo "TEST SUCCESS"