  sudo: required

  language: generic

  services:
    - docker
  
  before_install:
    - echo "start create images"
    - docker build -t a2/react -f Dockerfile.dev .
  
  script:
    - docker run -e CI=true a2/react echo "check"

  deploy:
    provider: elasticbeanstalk
    region: "ap-northeast-2"
    app: "docker-react-app"
    env: "dockerreactapp-env"
    bucket-name: "elasticbeanstalk-ap-northeast=2=069513091873"
    bucket_path: "docker-react-app"
    on:
      branch: main
      